openapi: 3.0.0
info:
  title: Plaid Institutions Search API
  version: 1.0.0
  description: API to search for financial institutions with specific criteria using Plaid.
servers:
  - url: 'https://sandbox.plaid.com'
    description: Plaid server
paths:
  /institutions/search:
    post:
      summary: Search for financial institutions
      operationId: searchInstitutions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequest'
      responses:
        '200':
          description: An array of institutions matching the search criteria.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
components:
  schemas:
    SearchRequest:
      type: object
      required:
        - client_id
        - secret
        - query
        - country_codes
      properties:
        client_id:
          type: string
          description: Your Plaid API client_id.
        secret:
          type: string
          description: Your Plaid API secret.
        query:
          type: string
          description: The search query. Institutions with names matching the query are returned.
          minLength: 1
        products:
          type: array
          items:
            type: string
            enum: ["assets", "auth", "balance", "employment", "identity", "income_verification", "investments", "liabilities", "identity_verification", "payment_initiation", "standing_orders", "transactions", "transfer"]
          description: Filter the Institutions based on whether they support all listed products.
          minItems: 1
        country_codes:
          type: array
          items:
            type: string
            enum: ["US", "GB", "ES", "NL", "FR", "IE", "CA", "DE", "IT", "PL", "DK", "NO", "SE", "EE", "LT", "LV", "PT", "BE"]
          description: Specify which country or countries to include institutions from.
        options:
          type: object
          properties:
            oauth:
              type: boolean
              description: Limit results to institutions with or without OAuth login flows.
            include_optional_metadata:
              type: boolean
              description: When true, return the institution's homepage URL, logo, and primary brand color.
            include_auth_metadata:
              type: boolean
              description: When true, returns metadata related to the Auth product indicating which auth methods are supported.
              default: false
            include_payment_initiation_metadata:
              type: boolean
              description: When true, returns metadata related to the Payment Initiation product indicating which payment configurations are supported.
              default: false
            payment_initiation:
              type: object
              properties:
                payment_id:
                  type: string
                  description: A unique ID identifying the payment.
                consent_id:
                  type: string
                  description: A unique ID identifying the payment consent.
    SearchResponse:
      type: object
      properties:
        institutions:
          type: array
          items:
            $ref: '#/components/schemas/Institution'
        request_id:
          type: string
          description: A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
    Institution:
      type: object
      properties:
        institution_id:
          type: string
          description: Unique identifier for the institution.
        name:
          type: string
          description: The official name of the institution.
        products:
          type: array
          items:
            type: string
            enum: ["assets", "auth", "balance", "employment", "identity", "income_verification", "investments", "liabilities", "identity_verification", "payment_initiation", "standing_orders", "transactions", "transfer"]
          description: A list of the Plaid products supported by the institution.
        country_codes:
          type: array
          items:
            type: string
            enum: ["US", "GB", "ES", "NL", "FR", "IE", "CA", "DE", "IT", "PL", "DK", "NO", "SE", "EE", "LT", "LV", "PT", "BE"]
          description: A list of the country codes supported by the institution.
        url:
          type: string
          nullable: true
          description: The URL for the institution's website.
        primary_color:
          type: string
          nullable: true
          description: Hexadecimal representation of the primary color used by the institution.
        logo:
          type: string
          nullable: true
          description: Base64 encoded representation of the institution's logo.
        routing_numbers:
          type: array
          items:
            type: string
          description: A partial list of routing numbers associated with the institution.
        dtc_numbers:
          type: array
          items:
            type: string
          description: A partial list of DTC numbers associated with the institution.
        oauth:
          type: boolean
          description: Indicates that the institution has an OAuth login flow.
        status:
          $ref: '#/components/schemas/InstitutionStatus'
    InstitutionStatus:
      type: object
      nullable: true
      properties:
        item_logins:
          $ref: '#/components/schemas/UpdateEntity' 
        transaction_updates: 
          $ref: '#/components/schemas/UpdateEntity'  
        auth: 
          $ref: '#/components/schemas/UpdateEntity'  
        identity: 
          $ref: '#/components/schemas/UpdateEntity'
        investments_updates:
          $ref: '#/components/schemas/UpdateEntity'
        liabilities_updates:
          $ref: '#/components/schemas/UpdateEntity'
        liabilities:
          $ref: '#/components/schemas/UpdateEntity'
        investments: 
          $ref: '#/components/schemas/UpdateEntity'
        health_incidents: 
          $ref: '#/components/schemas/HealthIncidents'
        payment_initiation_metadata:
          $ref: '#/components/schemas/PaymentInitiationMetadata'
        auth_metadata: 
          $ref: '#/components/schemas/AuthMetadata'
    Breakdown:
      type: object
      description: A detailed breakdown of the institution's performance for a request type. The values for success, error_plaid, and error_institution sum to 1. The time range used for calculating the breakdown may range from the most recent few minutes to the past six hours. In general, smaller institutions will show status that was calculated over a longer period of time. For Investment updates, which are refreshed less frequently, the period assessed may be 24 hours or more.
      properties:
        success:
          type: number
          format: double
          description: The percentage of login attempts that are successful, expressed as a decimal.
        error_plaid:
          type: number
          format: double
          description: The percentage of logins that are failing due to an internal Plaid issue, expressed as a decimal.
        error_institution:
          type: number
          format: double
          description: The percentage of logins that are failing due to an issue in the institution's system, expressed as a decimal.
        refresh_interval:
          type: string
          enum: ["NORMAL", "DELAYED", "STOPPED"]
          description: The refresh_interval may be DELAYED or STOPPED even when the success rate is high. This value is only returned for Transactions status breakdowns.
          
    UpdateEntity:
      type: object
      properties:
        status:
          type: string
          enum: ["HEALTHY", "DEGRADED", "DOWN"]
          deprecated: true
          description: This field is deprecated in favor of the breakdown object, which provides more granular institution health data.
        last_status_change:
          type: string
          format: date-time
          description: ISO 8601 formatted timestamp of the last status change for the institution.
        breakdown:
          $ref: '#/components/schemas/Breakdown'
          
    HealthIncidents:
      type: array
      items:
        $ref: '#/components/schemas/HealthIncident'
      nullable: true
      description: Details of recent health incidents associated with the institution.
    HealthIncident:
      type: object
      properties:
        start_date:
          type: string
          format: date-time
          description: The start date of the incident, in ISO 8601 format.
        end_date:
          type: string
          format: date-time
          nullable: true
          description: The end date of the incident, in ISO 8601 format.
        title:
          type: string
          description: The title of the incident.
        incident_updates:
          type: array
          items:
            $ref: '#/components/schemas/IncidentUpdate'
    IncidentUpdate:
      type: object
      properties:
        description:
          type: string
          description: The content of the update.
        status:
          type: string
          enum: ["INVESTIGATING", "IDENTIFIED", "SCHEDULED", "RESOLVED", "UNKNOWN"]
          description: The status of the incident.
        updated_date:
          type: string
          format: date-time
          description: The date when the update was published, in ISO 8601 format.
    PaymentInitiationMetadata:
      type: object
      nullable: true
      description: Metadata that captures what specific payment configurations an institution supports when making Payment Initiation requests.
      properties:
        supports_international_payments:
          type: boolean
          description: Indicates whether the institution supports payments from a different country.
        supports_sepa_instant:
          type: boolean
          description: Indicates whether the institution supports SEPA Instant payments.
        maximum_payment_amount:
          type: object
          additionalProperties:
            type: string
          description: A mapping of currency to maximum payment amount supported by the institution, denominated in the smallest unit of currency.
        supports_refund_details:
          type: boolean
          description: Indicates whether the institution supports returning refund details when initiating a payment.
        standing_order_metadata:
          $ref: '#/components/schemas/StandingOrderMetadata'
    StandingOrderMetadata:
      type: object
      nullable: true
      description: Metadata specifically related to valid Payment Initiation standing order configurations for the institution.
      properties:
        supports_standing_order_end_date:
          type: boolean
          description: Indicates whether the institution supports closed-ended standing orders by providing an end date.
        supports_standing_order_negative_execution_days:
          type: boolean
          description: This is only applicable to MONTHLY standing orders. Indicates whether the institution supports negative integers (-1 to -5) for setting up a MONTHLY standing order relative to the end of the month.
        valid_standing_order_intervals:
          type: array
          items:
            type: string
            enum: ["WEEKLY", "MONTHLY"]
          description: A list of the valid standing order intervals supported by the institution. Min length - 1.
    AuthMetadata:
      type: object
      nullable: true
      description: Metadata that captures information about the Auth features of an institution.
      properties:
        supported_methods:
          $ref: '#/components/schemas/SupportedMethods'
    SupportedMethods:
      type: object
      nullable: true
      description: Metadata specifically related to which auth methods an institution supports.
      properties:
        instant_auth:
          type: boolean
          description: Indicates if instant auth is supported.
        instant_match:
          type: boolean
          description: Indicates if instant match is supported.
        automated_micro_deposits:
          type: boolean
          description: Indicates if automated microdeposits are supported.
        instant_micro_deposits:
          type: boolean
          description: Indicates if instant microdeposits are supported.
          
          
          
          
          